### PR TITLE
Wrapping matic for payment

### LINKED ISSUE #58: UI should accept payments in MATIC rather than just wrapped matic
If the user doesn't have sufficient wrapped Matic in their wallet, the first transaction should be to wrap their matic and then proceed with the upload.

### PR DESCRIPTION
**Pull request by jamiehewitt15**
Fixes #58 

Steps for testing: 

1. Go to the preview link
2. make sure that you have Matic in your wallet but no Wrapped Matic. 
3. connect your wallet and check that you are on polygon mainnet. 
4. Choose a file to upload. 
5. Request a quote
6. Wrap your matic
7. Upload the file
8. Request the DDO link
9. Go to arweave.net/{TRANSACTION_ID} to check that the upload worked

### CODE REVIEW

**Comment by EnzoVezzaro** [comment]
there's some typescript errors caught by the build like this one:

Screenshot 2023-10-05 at 6 14 04 PM

Somehow the preview built the package anyway 😅 

for what I see on the preveiw, the wrap button is disabled for me even if I have MATIC on me. Also, if I try to get a quote, then button just changes to "WRAP MATIC" without showing the actual amount to pay. 

Screenshot 2023-10-05 at 6 29 50 PM

Tested on https://api.test.uploader.oceanprotocol.com/

UPDATE:

when I run the PR locally I see this error: 
Screenshot 2023-10-05 at 6 32 15 PM

**Comment by jamiehewitt15** [comment]
Thanks for testing @EnzoVezzaro. I fixed the missing quote payment amount and the build error. 

In the screenshot of the disabled Wrap Matic button, are you using polygon mainnet or another network? If you were on Mumbai it would give you that transaction reverted for an unknown reason error because this only works on polygon mainnet at the moment.

**Comment by EnzoVezzaro** [comment]
I made a small change for the label. I have 2 questions though:

- can we add mumbai on this PR to avoid having to spend MATIC on testing?
- right now we still say "MATIC" on the title of the token in polygon, but this needs to change to "WMATIC" as for contract ("0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270") - issue [here](https://github.com/oceanprotocol/uploader_arweave/issues/57), are we checking the balance for both MATIC and WMATIC or just WMATIC (calling the contract)?

**Comment by jamiehewitt15** [comment]
> are we checking the balance for both MATIC and WMATIC or just WMATIC (calling the contract)?

Yeah, so at the moment the "Wrap Matic" button would be disabled if you don't have any Matic in your wallet, although there isn't any error message that's shown or feedback to the user at the moment. So the UX there could still be improved.

**Comment by jamiehewitt15** [comment]
> right now we still say "MATIC" on the title of the token in polygon, but this needs to change to "WMATIC" as for contract ("0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270") 

That's been done on the Arweave microservice, I'll ask Marian to deploy it. 


> can we add mumbai on this PR to avoid having to spend MATIC on testing?

Yeah, I've added the contract Address for WMATIC on mumbai

**Comment by EnzoVezzaro** [comment]
I don't know 🥲 I need a little more time to review this PR. I feel like we're not explaining well what's happening. For me, it's a bit confusing why I need to convert all the time to have the upload going. For example:

Screenshot 2023-10-06 at 11 48 53 AM

here I have MATIC and WMATIC, but still I need to swap to finish the upload.

**Comment by jamiehewitt15** [comment]
Can you check the console for the log of your balance?

```
console.log('Check if user has wrapped matic in their wallet')
console.log('balanceData', balanceData)
```

**Comment by jamiehewitt15** [comment]
I tried to recreate that error with the following steps:
1. request quote
2. wrap matic
3. refresh page
4. Request quote again (but this time I have wrapped matic in my wallet)
5. This time, the "upload" button is shown directly bypassing the "Wrap Matic" step

(See video below)

https://www.loom.com/share/d60be29c09cc4468bf34c00b4b6e6396

What network are you testing on?

**Comment by EnzoVezzaro** [comment]
Also when you reject the transaction, the upload button kind of reset but it gets stuck.

https://www.loom.com/share/6363da9cee06418d8f55a69d1ed602cd?sid=9dcc7611-cbe8-4dac-af53-d0623f9dc4af

if you reject the "wrap matic" transaction, the app breaks. 

Screenshot 2023-10-06 at 3 48 35 PM

On mumbai I get this error:

Screenshot 2023-10-06 at 3 46 14 PM

**Comment by EnzoVezzaro** [comment]
probably this is due to mumbai. 

I have enough MATIC and WMATIC for the transaction, but I still see the "WRAP MATIC" button. I should see the "Upload" button directly.

Screenshot 2023-10-09 at 2 45 51 PM

I'm investigating the cause.

Screenshot 2023-10-09 at 2 45 34 PM

**Comment by jamiehewitt15** [comment]
The issue in the screenshot you shared above is that the contract call is made to the wrong WMATIC address for Mumbai. It should be fixed in the latest changes, could you test again?

**Comment by EnzoVezzaro** [comment]
i keep getting the following error on upload: 
`"Error uploading to IPFS: Error processing the uploaded files: File() got unexpected keyword arguments: 'content_type'"`

**Comment by jamiehewitt15** [comment]
> i keep getting the following error on upload: `"Error uploading to IPFS: Error processing the uploaded files: File() got unexpected keyword arguments: 'content_type'"`

Yeah true, not good timing. I broke something on the backend which I'm fixing separately to this. I'll let you know when it works again

**Comment by jamiehewitt15** [comment]
@EnzoVezzaro the backend issues are fixed now. Can you test again?

**Comment by EnzoVezzaro** [comment]
I found a couple of issues:

1. if you connect to polygon and then change to polygon mumbai, the app crashes

Screenshot 2023-10-12 at 12 09 38 PM

2. I still see "WRAP MATIC" even if I have enought WMATIC on my wallet

Screenshot 2023-10-12 at 12 10 09 PM

3. If you click "WRAP MATIC" and then you reject the tx, the app crashes

Screenshot 2023-10-12 at 12 10 24 PM

**Comment by EnzoVezzaro** [comment]
Hi @jamiehewitt15 I made some changes to this PR to solve some of the issues I commented. 
I fixed some minor thing I found, and also worked on the issues I found. 

Can you please just take a look at ALL of the SWAP MATIC states:

- user has MATIC, but not WMATIC --> show WRAP MATIC
- user has WMATIC, but it's not enough --> check if user has MATIC, if so, show WRAP MATIC
- user doesn't have MATIC nor WMATIC --> show error message, button is disabled
- user doesn't have MATIC, but has enough WMATIC --> show Upload
- user has MATIC and WMATIC --> show upload

not sure if I'm forgetting another state. If so (it's king of late and I'm kind of tired 😪), please let me know, but they should be all. 

Take a look and test it out please.

**Comment by EnzoVezzaro** [comment]
merging to update as much as possible

**Pull request merged**
